
import { GoogleGenAI } from "@google/genai";
import { GradingStyle } from "../types";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  async generateStyleReference(base64Image: string, style: GradingStyle): Promise<string> {
    const prompt = `
      Act as a world-class cinematic colorist. 
      Analyze this video still and generate a version with a "${style}" color grade.
      RULES:
      1. DO NOT change the subject, composition, or structure of the image.
      2. ONLY modify the lighting, color balance, contrast, and saturation.
      3. Use realistic, high-end film aesthetics (Rec.709 Gamma 2.4 compliant).
      4. The output must look like a frame from a professional movie or high-budget advertisement.
      Output only the modified image.
    `;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            { inlineData: { data: base64Image, mimeType: 'image/png' } },
            { text: prompt }
          ]
        }
      });

      let imageUrl = '';
      if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            imageUrl = `data:image/png;base64,${part.inlineData.data}`;
            break;
          }
        }
      }

      if (!imageUrl) throw new Error("No image generated by Gemini");
      return imageUrl;
    } catch (error) {
      console.error("Gemini Image Gen Error:", error);
      throw error;
    }
  }
}
